dist: trusty
language: csharp
mono: none
dotnet: 2.0.3

env:
- NUGET_API=https://api.nuget.org/v3/index.json

before_script:
- "ls -lhaF"

script:
- "dotnet test $TRAVIS_BUILD_DIR/Gov.NET.Tests/Gov.NET.Tests.csproj"

deploy:
  skip_cleanup: true
  provider: script
  script: script: dotnet pack -c Release && dotnet nuget push .vscode/build/Gov.NET.Core/bin/Release/Gov.NET.Core.*.nupkg -k $NUGET_API_KEY -s $NUGET_API && dotnet nuget push .vscode/build/Gov.NET.ProPublica/bin/Release/Gov.NET.ProPublica.*.nupkg -k $NUGET_API_KEY -s $NUGET_API && dotnet nuget push .vscode/build/Gov.NET/bin/Release/Gov.NET.*.nupkg -k $NUGET_API_KEY -s $NUGET_API
  on:
    branch: deploy