dist: trusty
language: csharp
mono: none
dotnet: 2.0.3

before_script:
  - "ls -lhaF"

script:
  - "dotnet test $TRAVIS_BUILD_DIR/Gov.NET.Tests/Gov.NET.Tests.csproj"

deploy:
  skip_cleanup: true
  provider: script
  before_script: dotnet pack -c Release
  script: echo "hello"
  on:
    branch: master