#!/usr/bin/env bash

MEMBER_PATH="GovLib.Examples/Members"

mkdir -p "$MEMBER_PATH"

# All Senators
sleep 1
curl "https://api.propublica.org/congress/v1/115/senate/members.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$MEMBER_PATH/get-all-senators.json"

# All Representatives
sleep 1
curl "https://api.propublica.org/congress/v1/115/house/members.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$MEMBER_PATH/get-all-representatives.json"

# Get Member By ID
sleep 1
curl "https://api.propublica.org/congress/v1/members/K000388.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$MEMBER_PATH/get-member-by-id.json"

# Get New Members
sleep 1
curl "https://api.propublica.org/congress/v1/members/new.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$MEMBER_PATH/get-new-members.json"

# Get Members By District
sleep 1
curl "https://api.propublica.org/congress/v1/members/senate/RI/current.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$MEMBER_PATH/get-members-by-district.json"

# Get Senators By State
sleep 1
curl "https://api.propublica.org/congress/v1/members/senate/RI/current.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$MEMBER_PATH/get-senators-by-state.json"

# Get Representatives By State
sleep 1
curl "https://api.propublica.org/congress/v1/members/house/GA/current.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$MEMBER_PATH/get-representatives-by-state.json"

# Get Representative From District
sleep 1
curl "https://api.propublica.org/congress/v1/members/house/GA/6/current.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$MEMBER_PATH/get-representative-from-disctrict.json"

# Get Senators Leaving Office
sleep 1
curl "https://api.propublica.org/congress/v1/115/senate/members/leaving.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$MEMBER_PATH/get-senators-leaving-office.json"

# Get Senators Leaving Office
sleep 1
curl "https://api.propublica.org/congress/v1/115/house/members/leaving.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$MEMBER_PATH/get-representatives-leaving-office.json"
