#!/usr/bin/env bash

export HERE=$(dirname "$(readlink -f "${0}")")

mkdir -p "$HERE/Examples/Members"

# All Senators
curl "https://api.propublica.org/congress/v1/115/senate/members.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-all-senators.json"
sleep 1

# All Representatives
curl "https://api.propublica.org/congress/v1/115/house/members.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-all-representatives.json"
sleep 1

# Get Specific Member
curl "https://api.propublica.org/congress/v1/members/K000388.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-specific-member.json"
sleep 1

# Get New Members
curl "https://api.propublica.org/congress/v1/members/new.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-new-members.json"
sleep 1

# Get Members By District
curl "https://api.propublica.org/congress/v1/members/senate/RI/current.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-members-by-district.json"
sleep 1

# Get Leaving Members
curl "https://api.propublica.org/congress/v1/115/house/members/leaving.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-leaving-members.json"
sleep 1

# Get Senators By State
curl "https://api.propublica.org/congress/v1/members/senate/RI/current.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-senators-by-state.json"
sleep 1

# Get Representatives By State
curl "https://api.propublica.org/congress/v1/members/house/GA/current.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-representatives-by-state.json"
sleep 1

# Get Representative From District
curl "https://api.propublica.org/congress/v1/members/house/GA/6/current.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-representative-from-disctrict.json"
sleep 1

# Get Senators Leaving Office
curl "https://api.propublica.org/congress/v1/115/senate/members/leaving.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-senators-leaving-office.json"
sleep 1

# Get Senators Leaving Office
curl "https://api.propublica.org/congress/v1/115/house/members/leaving.json" -H "X-API-Key: $PROPUBLICA_API_KEY" > "$HERE/Examples/Members/get-representatives-leaving-office.json"
sleep 1
